development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: slomo_development
  pool: 5
  host: localhost
  # username: root


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: slomo_test
  pool: 5
  host: localhost
  # username: root

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: slomo_production
  pool: 5
  host: localhost
  # username: root
